name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      
  - title: 'Documentation'
    labels:
      - 'update'
      - 'release'
      - 'translation'
  - title: 'Maintenance'
    label: 'chore'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: ' - No changes listed'
sort-by: merged_at
sort-direction: descending
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
    $CHANGES